# Generated by Django 5.2.4 on 2025-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=15)),
                ('date_of_birth', models.IntegerField()),
                ('house_name', models.CharField(max_length=20)),
                ('ward_number', models.IntegerField(max_length=2)),
            ],
        ),
    ]
