# Generated by Django 5.2.4 on 2025-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='ward_number',
            field=models.IntegerField(),
        ),
    ]
